### ISSUE TITLE
out of memory running text2image

### ISSUE THREAD

**Issue by rickyars** [nicolai256/Stable-textual-inversion_win#6]
i'm trying to run `text2image` but getting this error after training:
```
RuntimeError: CUDA out of memory. Tried to allocate 8.00 GiB (GPU 0; 15.90 GiB total capacity; 8.31 GiB already allocated; 6.32 GiB free; 8.70 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```
```
Thu Aug 25 01:58:00 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   40C    P0    27W / 250W |      0MiB / 16280MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by rickyars** [comment]
ah ha! dropping to 4 samples from 8 did the trick. sorry for being such an idiot. leaving this here for others.

**Comment by rickyars** [comment]
ah ha! dropping to 4 samples from 8 did the trick. sorry for being such an idiot. leaving this here for others.

**Comment by mabry1985** [comment]
Could you be more specific? Did you drop to 4 image samples? There are several reports of memory issues in the original Textual Inversion repo around this and I'm experiencing it as well. Anymore info would be helpful, thanks.
